package ru.donyka.chunkanimator.compat;

public final class SodiumShaderSourcePatcher {
    private static final String MARKER = "u_ChunkAnimatorEnabled";
    private static final String TRANSLATION_LINE = "    vec3 translation = u_RegionOffset + _get_draw_translation(_draw_id);";

    private SodiumShaderSourcePatcher() {
    }

    public static String patch(String source) {
        if (source == null || source.contains(MARKER) || !source.contains(TRANSLATION_LINE)) {
            return source;
        }

        String patched = source.replace("void main() {", shaderCode() + "\nvoid main() {");
        return patched.replace(
                TRANSLATION_LINE,
                "    vec3 chunkanimator_relative = _get_draw_translation(_draw_id);\n"
                        + "    vec3 translation = u_RegionOffset + chunkanimator_relative + chunkanimator_offset(chunkanimator_relative);"
        );
    }

    private static String shaderCode() {
        return String.join("\n",
                "uniform int u_ChunkAnimatorEnabled;",
                "uniform int u_ChunkAnimatorMode;",
                "uniform int u_ChunkAnimatorEasing;",
                "uniform int u_ChunkAnimatorCurrentTime;",
                "uniform int u_ChunkAnimatorDuration;",
                "uniform int u_ChunkAnimatorDisableAroundPlayer;",
                "uniform int u_ChunkAnimatorStartTimes[256];",
                "uniform float u_ChunkAnimatorMinY;",
                "uniform float u_ChunkAnimatorMaxY;",
                "uniform float u_ChunkAnimatorHorizon;",
                "uniform float u_ChunkAnimatorRegionOriginX;",
                "uniform float u_ChunkAnimatorRegionOriginY;",
                "uniform float u_ChunkAnimatorRegionOriginZ;",
                "uniform float u_ChunkAnimatorPlayerX;",
                "uniform float u_ChunkAnimatorPlayerZ;",
                "",
                "float chunkanimator_ease(float elapsed) {",
                "    if (u_ChunkAnimatorDuration <= 0) {",
                "        return 1.0;",
                "    }",
                "",
                "    float duration = float(u_ChunkAnimatorDuration);",
                "    float t = clamp(elapsed, 0.0, duration);",
                "",
                "    if (t >= duration) {",
                "        return 1.0;",
                "    }",
                "",
                "    float n = t / duration;",
                "",
                "    if (u_ChunkAnimatorEasing == 0) {",
                "        return n;",
                "    }",
                "",
                "    if (u_ChunkAnimatorEasing == 1) {",
                "        return -n * (n - 2.0);",
                "    }",
                "",
                "    if (u_ChunkAnimatorEasing == 2) {",
                "        n -= 1.0;",
                "        return n * n * n + 1.0;",
                "    }",
                "",
                "    if (u_ChunkAnimatorEasing == 3) {",
                "        n -= 1.0;",
                "        return -(n * n * n * n - 1.0);",
                "    }",
                "",
                "    if (u_ChunkAnimatorEasing == 4) {",
                "        n -= 1.0;",
                "        return n * n * n * n * n + 1.0;",
                "    }",
                "",
                "    if (u_ChunkAnimatorEasing == 5) {",
                "        return (n >= 1.0) ? 1.0 : (-pow(2.0, -10.0 * n) + 1.0);",
                "    }",
                "",
                "    if (u_ChunkAnimatorEasing == 6) {",
                "        return sin(n * 1.5707963267948966);",
                "    }",
                "",
                "    if (u_ChunkAnimatorEasing == 7) {",
                "        n -= 1.0;",
                "        return sqrt(max(0.0, 1.0 - n * n));",
                "    }",
                "",
                "    if (u_ChunkAnimatorEasing == 8) {",
                "        float s = 1.70158;",
                "        n -= 1.0;",
                "        return n * n * ((s + 1.0) * n + s) + 1.0;",
                "    }",
                "",
                "    if (u_ChunkAnimatorEasing == 9) {",
                "        if (n < 1.0 / 2.75) {",
                "            return 7.5625 * n * n;",
                "        } else if (n < 2.0 / 2.75) {",
                "            n -= 1.5 / 2.75;",
                "            return 7.5625 * n * n + 0.75;",
                "        } else if (n < 2.5 / 2.75) {",
                "            n -= 2.25 / 2.75;",
                "            return 7.5625 * n * n + 0.9375;",
                "        }",
                "",
                "        n -= 2.625 / 2.75;",
                "        return 7.5625 * n * n + 0.984375;",
                "    }",
                "",
                "    if (n <= 0.0 || n >= 1.0) {",
                "        return n;",
                "    }",
                "",
                "    return pow(2.0, -10.0 * n) * sin((n - 0.075) * 20.943951023931955) + 1.0;",
                "}",
                "",
                "vec3 chunkanimator_horizontal_offset(float elapsed, vec3 origin) {",
                "    float eased = chunkanimator_ease(elapsed) * 200.0;",
                "    float distance = -(200.0 - eased);",
                "    float differenceX = u_ChunkAnimatorPlayerX - (origin.x + 8.0);",
                "    float differenceZ = u_ChunkAnimatorPlayerZ - (origin.z + 8.0);",
                "",
                "    if (abs(differenceX) > abs(differenceZ)) {",
                "        return vec3((differenceX > 0.0 ? 1.0 : -1.0) * distance, 0.0, 0.0);",
                "    }",
                "",
                "    return vec3(0.0, 0.0, (differenceZ > 0.0 ? 1.0 : -1.0) * distance);",
                "}",
                "",
                "vec3 chunkanimator_offset(vec3 relative) {",
                "    if (u_ChunkAnimatorEnabled == 0 || u_ChunkAnimatorDuration <= 0) {",
                "        return vec3(0.0);",
                "    }",
                "",
                "    int sectionId = int(_draw_id);",
                "    int startTime = u_ChunkAnimatorStartTimes[sectionId];",
                "",
                "    if (startTime < 0) {",
                "        return vec3(0.0);",
                "    }",
                "",
                "    float elapsed = float(u_ChunkAnimatorCurrentTime - startTime);",
                "",
                "    if (elapsed < 0.0 || elapsed >= float(u_ChunkAnimatorDuration)) {",
                "        return vec3(0.0);",
                "    }",
                "",
                "    vec3 origin = vec3(u_ChunkAnimatorRegionOriginX, u_ChunkAnimatorRegionOriginY, u_ChunkAnimatorRegionOriginZ) + relative;",
                "",
                "    if (u_ChunkAnimatorDisableAroundPlayer != 0) {",
                "        float nearX = u_ChunkAnimatorPlayerX - (origin.x + 8.0);",
                "        float nearZ = u_ChunkAnimatorPlayerZ - (origin.z + 8.0);",
                "",
                "        if (nearX * nearX + nearZ * nearZ <= 4096.0) {",
                "            return vec3(0.0);",
                "        }",
                "    }",
                "",
                "    int mode = u_ChunkAnimatorMode;",
                "",
                "    if (mode == 2) {",
                "        mode = origin.y < u_ChunkAnimatorHorizon ? 0 : 1;",
                "    }",
                "",
                "    if (mode == 0) {",
                "        float distance = abs(origin.y - u_ChunkAnimatorMinY);",
                "        return vec3(0.0, -distance + chunkanimator_ease(elapsed) * distance, 0.0);",
                "    }",
                "",
                "    if (mode == 1) {",
                "        float distance = max(0.0, u_ChunkAnimatorMaxY - origin.y);",
                "        return vec3(0.0, distance - chunkanimator_ease(elapsed) * distance, 0.0);",
                "    }",
                "",
                "    if (mode == 3 || mode == 4) {",
                "        return chunkanimator_horizontal_offset(elapsed, origin);",
                "    }",
                "",
                "    return vec3(0.0);",
                "}");
    }
}
