org.gradle.jvmargs=-Xmx2G

minecraft_version=26.1.2
minecraft_dependency=>=26.1 <=26.1.2
loader_version=0.19.2
fabric_version=0.148.0+26.1.2
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
java_version=25

mod_version=1.0.0+26.1.x
maven_group=ru.donyka
archives_base_name=chunkanimator-fabric
